### ISSUE TITLE
Admin site returns server error

### ISSUE THREAD

**Issue by JosedeKruif** [UUDigitalHumanitieslab/texcavator#125]
When trying to open Django admin site, I get a 500 Internal server error.

**Comment by jgonggrijp** [comment]
The problem occurs on both servers. It does not occur on my local installation.

Stacktrace:

```
[12/May/2016 11:57:06] ERROR [django.request:256] Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 400, in login
    return login(request, **defaults)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/contrib/sites/models.py", line 62, in get_current
    return self._get_site_by_request(request)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/contrib/sites/models.py", line 46, in _get_site_by_request
    site = self.get(domain__iexact=host)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/texcavator/data/env/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Site matching query does not exist.
```

It appears that our code is not even being called before the exception comes up, so there must be some kind of inconsistency in the database. Unfortunately the MySQL logs don't show any clues. Perhaps something went wrong during deployment, so I think it is best if @mhkuu looks further into this.

**Comment by mhkuu** [comment]
Figured it out; I should have removed `django.contrib.sites` from the `settings.py` file after I removed the `SITE_ID` setting (which I thought was part of the flatpages app (see #85)). I'll resolve this next week.

**Comment by jgonggrijp** [comment]
I don't know how you figured that out, but you were right. I applied the fix today and deployed a new hotfix, so you don't have to do it next week.
